repos:
  - repo: local
    hooks:
      - id: make-lint
        name: Run Make Lint
        entry: make lint
        language: system
        stages:
          - commit

      - id: make-test
        name: Run Make Test
        entry: make test
        language: system
        stages:
          - push